apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoice-api
spec: 
  replicas: 1 
  selector:
    matchLabels:
      app: invoice-api
  template:
    metadata:
      labels:
        app: codebank
    spec: 
      containers:
        - name: invoice-api
          image: gomesdocker/imersao3-invoice-api:latest 
          volumeMounts:
            - name: invoice-api-volume
              mountPath: /home/node/app/.env
               subPath: .env
          ports:
            - containerPort: 3000
    
      volumes:
        - name: invoice-api-volume
          configMap:
            name: invoice-api-conf
            items:
              - key: env
                path: .env

 
